version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: 'maven:slim'
    steps:
      - checkout
      - run:
          name: Build and Test and Report
          command: mvn clean install jacoco:report coveralls:report