version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.0
    steps:
      - checkout
      - run:
          name: Build and Test and Report
          command: mvn clean install jacoco:report
      - run:
          name: CodeCov Report
          command: bash <(curl -s https://codecov.io/bash)