version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: 'maven:3-jdk-11-slim'
    steps:
      - checkout
      - run:
          name: Build and Test and Report
          command: mvn -DrepoToken=$COVERALLS_REPO_TOKEN clean install jacoco:report coveralls:report